version : '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    volumes: 
    - .:/app
    - /app/node_modules
    environment:
    - NODE_ENV=development


